name: cpp-conda
channels:
  - conda-forge
  - defaults
dependencies:
  # Build tools
  - cmake
  - make
  - clang
  - clang-tools # clang-format, clang-tidy
  - clangdev
  - clangxx
  - libclang
  - libclang-cpp
  - libclang-cpp11
  - gxx_linux-64 # C++ standard lib and gcc - https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  # Libraries
  - abseil-cpp # No version since "live at head"
  - xtensor=0.*
  - xtl=0.*
  - xsimd=7.*
  - nlohmann_json=3.*
  # Development
  - cmake_format
