name: cpp-conda
channels:
  - conda-forge
  - defaults
dependencies:
  # Build tools
  - cmake
  - make
  - clang-tools # clang-format, clang-tidy
  - libstdcxx-devel_linux-64
  - gxx_linux-64 # C++ standard lib and gcc - https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  # Libraries
  - abseil-cpp # No version since "live at head" - https://abseil.io/about/philosophy#we-recommend-that-you-choose-to-live-at-head
  - xtensor=0.*
  - xtl=0.*
  - xsimd=7.*
  - nlohmann_json=3.*
  - protobuf=3.* # includes Protobuf compiler, C++ headers, Python libraries
  # Development
  - cmake_format
